"""Output Filtering and Leak Prevention Module (CMP-10).

Inspects assistant response chunks and full texts to prevent secret leakage,
system prompt disclosures, and ungrounded fabrications.
"""

from __future__ import annotations

import re
import structlog

logger = structlog.get_logger(__name__)

# Patterns for sensitive credentials or system internals
SENSITIVE_PATTERNS: list[tuple[str, re.Pattern]] = [
    ("OPENAI_KEY", re.compile(r"sk-[a-zA-Z0-9_\-]{20,}")),
    ("HF_TOKEN", re.compile(r"hf_[a-zA-Z0-9]{30,}")),
    ("DB_CONNECTION_STRING", re.compile(r"postgresql(\+asyncpg)?://[^\s]+")),
    ("REDIS_CONNECTION_STRING", re.compile(r"redis://[^\s]+")),
]


def sanitize_response(content: str) -> str:
    """Filter sensitive secrets, tokens, or connection strings from response text.

    Args:
        content: Raw output string generated by LLM.

    Returns:
        Sanitized content with secrets masked.
    """
    sanitized = content
    for label, pattern in SENSITIVE_PATTERNS:
        if pattern.search(sanitized):
            logger.error("Blocked sensitive pattern in generated response", pattern=label)
            sanitized = pattern.sub("[REDACTED_SECRET]", sanitized)

    return sanitized


def validate_grounding(response: str, evidence_ids: list[str]) -> bool:
    """Check whether response stays grounded within returned evidence when POIs are cited.

    Args:
        response: Output text.
        evidence_ids: List of valid entity IDs fetched from Tools/Knowledge.

    Returns:
        True if check passes, False if unverified entity citation detected.
    """
    # Simple heuristic: if entity format like POI_xxx or KB_xxx is mentioned,
    # verify it exists in evidence_ids
    cited_ids = re.findall(r"\b(POI_\d+|KB_\d+[A-Za-z0-9_]*)\b", response)
    for cid in cited_ids:
        if cid not in evidence_ids:
            logger.warning("Detected potentially ungrounded entity ID in response", entity_id=cid)
            return False
    return True
