"""Redis cache manager for tool response idempotency and API rate limiting.

Manages short-lived tool output cache at key tool_cache:{hash} (5m TTL) and
rate limiting sliding/fixed windows at key rate:{ip} (1m TTL).
"""

from __future__ import annotations

import hashlib
import json
from typing import Any, Protocol, runtime_checkable

import structlog
from redis.asyncio import Redis

logger = structlog.get_logger(__name__)


@runtime_checkable
class CacheManagerProtocol(Protocol):
    """Structural interface for tool caching and rate limiting."""

    def make_cache_key(self, tool_name: str, params: dict[str, Any]) -> str:
        """Generate deterministic cache key based on tool parameters."""
        ...

    async def get_cached(self, key: str) -> dict[str, Any] | None:
        """Retrieve cached tool response."""
        ...

    async def set_cached(self, key: str, value: dict[str, Any], ttl_seconds: int = 300) -> None:
        """Store tool response in cache with TTL."""
        ...

    async def is_rate_limited(
        self, identifier: str, limit: int = 60, window_seconds: int = 60
    ) -> bool:
        """Check if request count exceeds limit for identifier."""
        ...


class CacheManager(CacheManagerProtocol):
    """Redis adapter implementing CacheManagerProtocol."""

    def __init__(self, redis_client: Redis) -> None:
        """Initialize the cache manager.

        Args:
            redis_client: Async Redis client connection.
        """
        self._redis = redis_client

    def make_cache_key(self, tool_name: str, params: dict[str, Any]) -> str:
        """Compute MD5 hash over sorted parameter dictionary for deterministic caching.

        Args:
            tool_name: Name of tool (e.g., 'poi_search').
            params: Parameters dictionary passed to the tool.

        Returns:
            Namespaced cache key string 'tool_cache:{hash}'.
        """
        serialized = json.dumps(params, sort_keys=True, ensure_ascii=False)
        digest = hashlib.md5(f"{tool_name}:{serialized}".encode()).hexdigest()
        return f"tool_cache:{digest}"

    async def get_cached(self, key: str) -> dict[str, Any] | None:
        """Fetch cached tool response from Redis.

        Args:
            key: Cache key generated by make_cache_key.

        Returns:
            Cached dictionary or None if key is absent.
        """
        raw_val = await self._redis.get(key)
        if not raw_val:
            return None
        try:
            return json.loads(raw_val)
        except Exception as exc:
            logger.warning("Cache deserialization error", key=key, error=str(exc))
            return None

    async def set_cached(self, key: str, value: dict[str, Any], ttl_seconds: int = 300) -> None:
        """Store tool execution result in Redis with TTL.

        Args:
            key: Cache key string.
            value: Data dictionary to cache.
            ttl_seconds: Cache validity duration in seconds (default: 300s = 5m).
        """
        payload = json.dumps(value, ensure_ascii=False)
        await self._redis.set(key, payload, ex=ttl_seconds)

    async def is_rate_limited(
        self,
        identifier: str,
        limit: int = 60,
        window_seconds: int = 60,
    ) -> bool:
        """Check and increment sliding/fixed window request counter for identifier.

        Args:
            identifier: Client IP or token identifier.
            limit: Maximum allowed requests within the window.
            window_seconds: Duration of the rate window in seconds.

        Returns:
            True if request exceeds limit (rate limited), False if within quota.
        """
        key = f"rate:{identifier.strip()}"
        current = await self._redis.incr(key)
        if current == 1:
            await self._redis.expire(key, window_seconds)

        if current > limit:
            logger.warning("Rate limit exceeded for client", identifier=identifier, count=current)
            return True
        return False
